# Generated by Django 4.0 on 2021-12-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.IntegerField(max_length=15)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
