# Generated by Django 4.0 on 2021-12-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000000000)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=130)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
